### ISSUE TITLE
Please share the mistake that TE made that allowed decryption.

### ISSUE THREAD

**Issue by wmealing** [billymeter/rez#1]
They may have made the same mistake with the EP-133.  Maybe I can use that with that firmware.

See my github profile if you want to email.  Thanks in advance.

**Comment by Tolsi** [comment]
As far as I remember, when connected to the serial port when flashing the firmware, the device sent several decrypted bytes of the firmware, which made it possible to rearrange subsequent bytes of the firmware to the right address (at which bytes were decrypted and published) and thus extract the entire decrypted firmware in a week during thousands of reboots/reflashes. The device's firmware did not contain Easter eggs or anything interesting.

**Comment by wmealing** [comment]
I'm wondering if it had a cryptographic key, as they may be using the same key in other firmware for other devices they sell.

Thanks for the information, its going to be a long learning process.

**Comment by wmealing** [comment]
Ok, initial testing , my hardware is not behaving the same way.  Looks like i'm going to have to go grab the firmware off the chip itself.

**Comment by Tolsi** [comment]
Please, share it after that, it can be useful for someone! When I tried to repair my op1 I also don't have this dump before I found the way to read it.
